version: '3'
services:
  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./postgres_bootstrap.sql:/docker-entrypoint-initdb.d/postgres_bootstrap.sql
      - ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts down